package br.com.poo.mongo.presentation;

import br.com.poo.mongo.common.exception.CandidatoInexistenteExcepition;
import br.com.poo.mongo.common.exception.NumeroErradoException;
import br.com.poo.mongo.common.exception.VotarCandidatoInexistenteException;
import br.com.poo.mongo.common.vo.CandidatosVO;
import br.com.poo.mongo.common.vo.VotosVO;
import br.com.poo.mongo.service.ServiceCandidato;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author nirto
 */
public class UrnaSwing extends javax.swing.JFrame {

    private StringBuilder numeroCandidato;
    private ServiceCandidato service;
    boolean votoBranco;
    private VotosVO votos = new VotosVO();
    JFrame frame = new JFrame();

    //  private JTextField textFieldDigitos[];
    /**
     * Creates new form UrnaSwing
     */
    public UrnaSwing() {
        initComponents();
        numeroCandidato = new StringBuilder();
        service = new ServiceCandidato();
        iniciarVotacao();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Camadas = new javax.swing.JLayeredPane();
        jPanelInfoVereador = new javax.swing.JPanel();
        lblFim = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblVereador = new javax.swing.JLabel();
        lblVereadora = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblPartido = new javax.swing.JLabel();
        lblNomeCandidato = new javax.swing.JLabel();
        lblNomePartido = new javax.swing.JLabel();
        lblMensageExeption = new javax.swing.JLabel();
        lblVotoBranco = new javax.swing.JLabel();
        lblSeuVoto = new javax.swing.JLabel();
        lblMensageTipoVoto = new javax.swing.JLabel();
        UIManager.put("jProgressBar.background", new java.awt.Color(0,153,0));
        jProgressBar = new javax.swing.JProgressBar();
        jNumeros = new javax.swing.JPanel();
        txtNumero2 = new javax.swing.JTextField();
        txtNumero1 = new javax.swing.JTextField();
        txtNumero4 = new javax.swing.JTextField();
        txtNumero3 = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        jInfoConfirma = new javax.swing.JPanel();
        lblInfoTeclas = new javax.swing.JLabel();
        lblInfoConfirma = new javax.swing.JLabel();
        lblInfoCorrige = new javax.swing.JLabel();
        lblTela = new javax.swing.JLabel();
        jTeclado = new javax.swing.JPanel();
        lblN1 = new javax.swing.JLabel();
        lblN2 = new javax.swing.JLabel();
        lblN3 = new javax.swing.JLabel();
        lblN4 = new javax.swing.JLabel();
        lblN5 = new javax.swing.JLabel();
        lblN6 = new javax.swing.JLabel();
        lblN7 = new javax.swing.JLabel();
        lblN8 = new javax.swing.JLabel();
        lblN9 = new javax.swing.JLabel();
        lblN0 = new javax.swing.JLabel();
        lblBranco = new javax.swing.JLabel();
        lblCorrige = new javax.swing.JLabel();
        lblPtaBaixo7 = new javax.swing.JLabel();
        lblBaixoTec = new javax.swing.JLabel();
        lblConfirma = new javax.swing.JLabel();
        lblPtaBaixo9 = new javax.swing.JLabel();
        lblLadoEsqTec = new javax.swing.JLabel();
        lblLadoDirTec = new javax.swing.JLabel();
        lblFaixaDireita = new javax.swing.JLabel();
        lblTopo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("br/com/poo/mongo/presentation/Bundle"); // NOI18N
        setTitle(bundle.getString("UrnaSwing.title")); // NOI18N
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(964, 618));
        setMinimumSize(new java.awt.Dimension(964, 618));
        setPreferredSize(new java.awt.Dimension(990, 650));
        setResizable(false);

        Camadas.setBackground(new java.awt.Color(255, 255, 255));
        Camadas.setForeground(new java.awt.Color(255, 255, 255));
        Camadas.setAutoscrolls(true);
        Camadas.setDoubleBuffered(true);
        Camadas.setFocusCycleRoot(true);
        Camadas.setFocusTraversalPolicyProvider(true);
        Camadas.setMaximumSize(new java.awt.Dimension(1000, 610));
        Camadas.setMinimumSize(new java.awt.Dimension(1000, 610));
        Camadas.setOpaque(true);
        Camadas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelInfoVereador.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInfoVereador.setMaximumSize(new java.awt.Dimension(2147483647, 588));
        jPanelInfoVereador.setMinimumSize(new java.awt.Dimension(632, 588));
        jPanelInfoVereador.setPreferredSize(new java.awt.Dimension(632, 588));
        jPanelInfoVereador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFim.setFont(new java.awt.Font("Arial", 0, 150)); // NOI18N
        lblFim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFim.setText(bundle.getString("UrnaSwing.lblFim.text")); // NOI18N
        jPanelInfoVereador.add(lblFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 320, 240));

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblImage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblImage.setMaximumSize(new java.awt.Dimension(112, 116));
        lblImage.setMinimumSize(new java.awt.Dimension(112, 116));
        lblImage.setPreferredSize(new java.awt.Dimension(112, 116));
        jPanelInfoVereador.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 112, 116));

        lblVereador.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        lblVereador.setText(bundle.getString("UrnaSwing.lblVereador.text")); // NOI18N
        lblVereador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelInfoVereador.add(lblVereador, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        lblVereadora.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        lblVereadora.setText(bundle.getString("UrnaSwing.lblVereadora.text")); // NOI18N
        lblVereadora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelInfoVereador.add(lblVereadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        lblNumero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNumero.setText(bundle.getString("UrnaSwing.lblNumero.text")); // NOI18N
        lblNumero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelInfoVereador.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        lblNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNome.setText(bundle.getString("UrnaSwing.lblNome.text")); // NOI18N
        lblNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelInfoVereador.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        lblPartido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPartido.setText(bundle.getString("UrnaSwing.lblPartido.text")); // NOI18N
        lblPartido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelInfoVereador.add(lblPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        lblNomeCandidato.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblNomeCandidato.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomeCandidato.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelInfoVereador.add(lblNomeCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 200, 20));

        lblNomePartido.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblNomePartido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomePartido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblNomePartido.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanelInfoVereador.add(lblNomePartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 40, 30));

        lblMensageExeption.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblMensageExeption.setText(bundle.getString("UrnaSwing.lblMensageExeption.text")); // NOI18N
        jPanelInfoVereador.add(lblMensageExeption, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 360, 30));

        lblVotoBranco.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblVotoBranco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVotoBranco.setText(bundle.getString("UrnaSwing.lblVotoBranco.text")); // NOI18N
        jPanelInfoVereador.add(lblVotoBranco, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 325, 410, 90));

        lblSeuVoto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSeuVoto.setText(bundle.getString("UrnaSwing.lblSeuVoto.text")); // NOI18N
        lblSeuVoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelInfoVereador.add(lblSeuVoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 130, 30));

        lblMensageTipoVoto.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblMensageTipoVoto.setText(bundle.getString("UrnaSwing.lblMensageTipoVoto.text")); // NOI18N
        jPanelInfoVereador.add(lblMensageTipoVoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 350, 50));

        jProgressBar.setBackground(new java.awt.Color(0, 153, 0));
        jProgressBar.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jProgressBar.setForeground(new java.awt.Color(0, 0, 0));
        jProgressBar.setAutoscrolls(true);
        jProgressBar.setBorderPainted(false);
        jProgressBar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jProgressBar.setDoubleBuffered(true);
        jProgressBar.setFocusCycleRoot(true);
        jProgressBar.setFocusTraversalPolicyProvider(true);
        jProgressBar.setInheritsPopupMenu(true);
        jProgressBar.setName(""); // NOI18N
        jProgressBar.setStringPainted(true);
        jPanelInfoVereador.add(jProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 400, 30));

        jNumeros.setBackground(new java.awt.Color(214, 214, 214));
        jNumeros.setOpaque(false);
        jNumeros.setLayout(new java.awt.GridBagLayout());

        txtNumero2.setEditable(false);
        txtNumero2.setBackground(new java.awt.Color(214, 214, 214));
        txtNumero2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNumero2.setFocusable(false);
        txtNumero2.setRequestFocusEnabled(false);
        txtNumero2.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jNumeros.add(txtNumero2, gridBagConstraints);

        txtNumero1.setEditable(false);
        txtNumero1.setBackground(new java.awt.Color(214, 214, 214));
        txtNumero1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNumero1.setFocusable(false);
        txtNumero1.setRequestFocusEnabled(false);
        txtNumero1.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jNumeros.add(txtNumero1, gridBagConstraints);

        txtNumero4.setEditable(false);
        txtNumero4.setBackground(new java.awt.Color(214, 214, 214));
        txtNumero4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNumero4.setFocusable(false);
        txtNumero4.setMaximumSize(new java.awt.Dimension(7, 20));
        txtNumero4.setRequestFocusEnabled(false);
        txtNumero4.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jNumeros.add(txtNumero4, gridBagConstraints);

        txtNumero3.setEditable(false);
        txtNumero3.setBackground(new java.awt.Color(214, 214, 214));
        txtNumero3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNumero3.setFocusable(false);
        txtNumero3.setRequestFocusEnabled(false);
        txtNumero3.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jNumeros.add(txtNumero3, gridBagConstraints);

        txtNumero.setEditable(false);
        txtNumero.setBackground(new java.awt.Color(214, 214, 214));
        txtNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNumero.setFocusable(false);
        txtNumero.setRequestFocusEnabled(false);
        txtNumero.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtNumero.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jNumeros.add(txtNumero, gridBagConstraints);

        jPanelInfoVereador.add(jNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, 40));

        jInfoConfirma.setBackground(new java.awt.Color(214, 214, 214));
        jInfoConfirma.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jInfoConfirma.setMaximumSize(new java.awt.Dimension(549, 77));
        jInfoConfirma.setMinimumSize(new java.awt.Dimension(549, 77));
        jInfoConfirma.setLayout(new java.awt.GridBagLayout());

        lblInfoTeclas.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lblInfoTeclas.setText(bundle.getString("UrnaSwing.lblInfoTeclas.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jInfoConfirma.add(lblInfoTeclas, gridBagConstraints);

        lblInfoConfirma.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lblInfoConfirma.setText(bundle.getString("UrnaSwing.lblInfoConfirma.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 0);
        jInfoConfirma.add(lblInfoConfirma, gridBagConstraints);

        lblInfoCorrige.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lblInfoCorrige.setText(bundle.getString("UrnaSwing.lblInfoCorrige.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 24, 0, 0);
        jInfoConfirma.add(lblInfoCorrige, gridBagConstraints);

        jPanelInfoVereador.add(jInfoConfirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 464, 549, 77));

        lblTela.setBackground(new java.awt.Color(255, 255, 255));
        lblTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/tela.jpg"))); // NOI18N
        lblTela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelInfoVereador.add(lblTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 14, 642, 603));

        Camadas.add(jPanelInfoVereador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 590));

        jTeclado.setBackground(new java.awt.Color(255, 255, 255));
        jTeclado.setAutoscrolls(true);
        jTeclado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTeclado.setMaximumSize(new java.awt.Dimension(324, 588));
        jTeclado.setMinimumSize(new java.awt.Dimension(324, 588));
        jTeclado.setPreferredSize(new java.awt.Dimension(324, 588));
        jTeclado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n1.jpg"))); // NOI18N
        lblN1.setAlignmentY(0.0F);
        lblN1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN1MouseReleased(evt);
            }
        });
        jTeclado.add(lblN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 261, -1, -1));

        lblN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n2.jpg"))); // NOI18N
        lblN2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN2MouseReleased(evt);
            }
        });
        jTeclado.add(lblN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 261, -1, -1));

        lblN3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n3.jpg"))); // NOI18N
        lblN3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN3MouseReleased(evt);
            }
        });
        jTeclado.add(lblN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 261, -1, -1));

        lblN4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n4.jpg"))); // NOI18N
        lblN4.setAlignmentY(0.0F);
        lblN4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN4MouseReleased(evt);
            }
        });
        jTeclado.add(lblN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 319, -1, -1));

        lblN5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n5.jpg"))); // NOI18N
        lblN5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN5MouseReleased(evt);
            }
        });
        jTeclado.add(lblN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 319, -1, -1));

        lblN6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n6.jpg"))); // NOI18N
        lblN6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN6MouseReleased(evt);
            }
        });
        jTeclado.add(lblN6, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 319, -1, -1));

        lblN7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n7.jpg"))); // NOI18N
        lblN7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN7MouseReleased(evt);
            }
        });
        jTeclado.add(lblN7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 379, -1, -1));

        lblN8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n8.jpg"))); // NOI18N
        lblN8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN8MouseReleased(evt);
            }
        });
        jTeclado.add(lblN8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 379, -1, -1));

        lblN9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n9.jpg"))); // NOI18N
        lblN9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN9MouseReleased(evt);
            }
        });
        jTeclado.add(lblN9, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 379, -1, -1));

        lblN0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n0.jpg"))); // NOI18N
        lblN0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN0MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN0MouseReleased(evt);
            }
        });
        jTeclado.add(lblN0, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 437, -1, -1));

        lblBranco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/branco.jpg"))); // NOI18N
        lblBranco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBranco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBrancoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBrancoMouseReleased(evt);
            }
        });
        jTeclado.add(lblBranco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 487, -1, -1));

        lblCorrige.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/corrige.jpg"))); // NOI18N
        lblCorrige.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCorrige.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCorrigeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblCorrigeMouseReleased(evt);
            }
        });
        jTeclado.add(lblCorrige, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 487, -1, -1));

        lblPtaBaixo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/ptabaixo7.jpg"))); // NOI18N
        jTeclado.add(lblPtaBaixo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 437, -1, -1));

        lblBaixoTec.setBackground(new java.awt.Color(255, 255, 255));
        lblBaixoTec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/abaixoTec.jpg"))); // NOI18N
        jTeclado.add(lblBaixoTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 546, -1, -1));

        lblConfirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/confirma.jpg"))); // NOI18N
        lblConfirma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblConfirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblConfirmaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblConfirmaMouseReleased(evt);
            }
        });
        jTeclado.add(lblConfirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 476, -1, -1));

        lblPtaBaixo9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/ptabaixo9.jpg"))); // NOI18N
        jTeclado.add(lblPtaBaixo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 437, -1, -1));

        lblLadoEsqTec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/ladoEsqTec.jpg"))); // NOI18N
        jTeclado.add(lblLadoEsqTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 261, -1, -1));

        lblLadoDirTec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/ladoDirTec.jpg"))); // NOI18N
        jTeclado.add(lblLadoDirTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 261, -1, -1));

        lblFaixaDireita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/faixaDir.jpg"))); // NOI18N
        jTeclado.add(lblFaixaDireita, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 35, -1, -1));

        lblTopo.setBackground(new java.awt.Color(255, 255, 255));
        lblTopo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/topo.jpg"))); // NOI18N
        jTeclado.add(lblTopo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Camadas.add(jTeclado, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 11, 370, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Camadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Camadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void lblN1MousePressed(MouseEvent evt) {//GEN-FIRST:event_lblN1MousePressed
        lblN1.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n1_down.jpg"));
            testeIndiceNumeroCandidato("1");

    }//GEN-LAST:event_lblN1MousePressed


    private void lblN1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN1MouseReleased
        lblN1.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n1.jpg"));
    }//GEN-LAST:event_lblN1MouseReleased

    private void lblN2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN2MousePressed
        lblN2.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n2_down.jpg"));
        testeIndiceNumeroCandidato("2");
    }//GEN-LAST:event_lblN2MousePressed

    private void lblN2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN2MouseReleased
        lblN2.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n2.jpg"));
    }//GEN-LAST:event_lblN2MouseReleased

    private void lblN3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN3MousePressed
        lblN3.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n3_down.jpg"));
        testeIndiceNumeroCandidato("3");
    }//GEN-LAST:event_lblN3MousePressed

    private void lblN3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN3MouseReleased
        lblN3.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n3.jpg"));
    }//GEN-LAST:event_lblN3MouseReleased

    private void lblN4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN4MousePressed
        lblN4.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n4_down.jpg"));
        testeIndiceNumeroCandidato("4");
    }//GEN-LAST:event_lblN4MousePressed

    private void lblN4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN4MouseReleased
        lblN4.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n4.jpg"));
    }//GEN-LAST:event_lblN4MouseReleased

    private void lblN5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN5MousePressed
        lblN5.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n5_down.jpg"));
        testeIndiceNumeroCandidato("5");
    }//GEN-LAST:event_lblN5MousePressed

    private void lblN5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN5MouseReleased
        lblN5.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n5.jpg"));
    }//GEN-LAST:event_lblN5MouseReleased

    private void lblN6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN6MousePressed
        lblN6.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n6_down.jpg"));
        testeIndiceNumeroCandidato("6");
    }//GEN-LAST:event_lblN6MousePressed

    private void lblN6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN6MouseReleased
        lblN6.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n6.jpg"));
    }//GEN-LAST:event_lblN6MouseReleased

    private void lblN7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN7MousePressed
        lblN7.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n7_down.jpg"));
        testeIndiceNumeroCandidato("7");
    }//GEN-LAST:event_lblN7MousePressed

    private void lblN7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN7MouseReleased
        lblN7.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n7.jpg"));
    }//GEN-LAST:event_lblN7MouseReleased

    private void lblN8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN8MousePressed
        lblN8.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n8_down.jpg"));
        testeIndiceNumeroCandidato("8");
    }//GEN-LAST:event_lblN8MousePressed

    private void lblN8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN8MouseReleased
        lblN8.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n8.jpg"));
    }//GEN-LAST:event_lblN8MouseReleased

    private void lblN9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN9MousePressed
        lblN9.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n9_down.jpg"));
        testeIndiceNumeroCandidato("9");
    }//GEN-LAST:event_lblN9MousePressed

    private void lblN9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN9MouseReleased
        lblN9.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n9.jpg"));
    }//GEN-LAST:event_lblN9MouseReleased

    private void lblN0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN0MousePressed
        lblN0.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n0_down.jpg"));
        testeIndiceNumeroCandidato("0");
    }//GEN-LAST:event_lblN0MousePressed

    private void lblN0MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN0MouseReleased
        lblN0.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n0.jpg"));
    }//GEN-LAST:event_lblN0MouseReleased

    private void lblBrancoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBrancoMousePressed
        lblBranco.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/branco_down.jpg"));
        tocarSom("SomTecla");
        jNumeros.setVisible(false);
        lblVotoBranco.setText("VOTO EM BRANCO");
        lblSeuVoto.setVisible(true);
        lblVotoBranco.setVisible(true);
        votoBranco = true;
        jInfoConfirma.setVisible(true);
        lblMensageTipoVoto.setVisible(false);
        lblVereadora.setVisible(false);
    }//GEN-LAST:event_lblBrancoMousePressed

    private void lblBrancoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBrancoMouseReleased
        lblBranco.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/branco.jpg"));
    }//GEN-LAST:event_lblBrancoMouseReleased

    private void lblCorrigeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCorrigeMousePressed
        lblCorrige.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/corrige_down.jpg"));
        tocarSom("SomTecla");
        corrigir();
    }//GEN-LAST:event_lblCorrigeMousePressed


    private void lblCorrigeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCorrigeMouseReleased
        lblCorrige.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/corrige.jpg"));
    }//GEN-LAST:event_lblCorrigeMouseReleased

    private void lblConfirmaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmaMousePressed
        lblConfirma.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/confirma_down.jpg"));

        /*if(numeroCandidato.toString().equals("99999")){
            }*/
        if (votoBranco) {
            
            System.out.println("Quantidade Votos: "+ service.votarBranco().getVotosBrancos());
            
        } else {
            try {
                service.votar(Integer.parseInt(numeroCandidato.toString()));
            } catch (VotarCandidatoInexistenteException ex) {

                service.votarNulo();
            }
        }
        tocarSom("inter");

        new FinalizarVoto().start();
        
        

    }//GEN-LAST:event_lblConfirmaMousePressed

    private void lblConfirmaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmaMouseReleased
        lblConfirma.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/confirma.jpg"));
    }//GEN-LAST:event_lblConfirmaMouseReleased

    private void iniciarVotacao() {
        jPanelInfoVereador.setVisible(true);
        lblNome.setVisible(false);
        lblNumero.setVisible(false);
        lblVereador.setVisible(true);
        lblPartido.setVisible(false);
        lblNomePartido.setText("");
        lblNomeCandidato.setText("");
        lblImage.setVisible(false);
        lblSeuVoto.setVisible(false);
        jInfoConfirma.setVisible(false);
        jProgressBar.setVisible(false);
        jNumeros.setVisible(true);
        lblNomePartido.setVisible(true);
        lblNomeCandidato.setVisible(true);
        lblFim.setText("FIM");
        lblFim.setVisible(false);
        lblMensageExeption.setVisible(false);
        lblVotoBranco.setVisible(false);
        votoBranco = false;
        lblMensageTipoVoto.setVisible(false);
    }

    private void imprimirPartido() {
        CandidatosVO vo = null;
        try {
            vo = service.getInfoPartido(Integer.parseInt(numeroCandidato.toString()));
            lblNomePartido.setText(vo.getPartido());
            lblSeuVoto.setVisible(true);

        } catch (NumeroErradoException ex) {
            lblMensageExeption.setVisible(true);
            lblMensageExeption.setText(ex.getMessage());
            lblMensageTipoVoto.setVisible(true);
            lblMensageTipoVoto.setText("VOTO NULO");
        }

    }

    private void imprimirCandidato() {
        CandidatosVO vo = null;
        try {
            vo = service.getInfoCandidatos(Integer.parseInt(numeroCandidato.toString()));
            if (vo.getNumeroCandidato() == 91003 || vo.getNumeroCandidato() == 92003
                    || vo.getNumeroCandidato() == 93003 || vo.getNumeroCandidato() == 94001
                    || vo.getNumeroCandidato() == 94002 || vo.getNumeroCandidato() == 95002
                    || vo.getNumeroCandidato() == 95003) {
                lblVereadora.setVisible(true);

            }
            lblImage.setVisible(true);
            lblImage.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/candidatos/" + vo.getNumeroCandidato() + ".png"));
            lblNomeCandidato.setText(vo.getNome());
        } catch (CandidatoInexistenteExcepition ex) {
            lblNome.setVisible(false);
            lblMensageExeption.setVisible(true);
            lblMensageExeption.setText(ex.getMessage());
            lblMensageTipoVoto.setVisible(true);
            lblMensageTipoVoto.setText("VOTO NULO");
        }

    }

    private void corrigir() {

        txtNumero.setText("");
        txtNumero1.setText("");
        txtNumero2.setText("");
        txtNumero3.setText("");
        txtNumero4.setText("");
        lblNomeCandidato.setText("");
        lblNomePartido.setText("");
        lblNome.setVisible(false);
        lblNumero.setVisible(false);
        lblPartido.setVisible(false);
        lblImage.setIcon(null);
        lblImage.setVisible(false);
        numeroCandidato.setLength(0);
        jInfoConfirma.setVisible(false);
        lblSeuVoto.setVisible(false);
        lblMensageExeption.setVisible(false);
        lblVotoBranco.setVisible(false);
        jNumeros.setVisible(true);
        lblMensageTipoVoto.setVisible(false);
        lblVereadora.setVisible(false);
    }

    private void testeIndiceNumeroCandidato(String auxNumCandidato) {
        if (txtNumero.getText().equals("")) {
            tocarSom("SomTecla");
            txtNumero.setText(auxNumCandidato);
            numeroCandidato.append(auxNumCandidato);
            return;
        }
        if (txtNumero1.getText().equals("")) {
            tocarSom("SomTecla");
            txtNumero1.setText(auxNumCandidato);
            numeroCandidato.append(auxNumCandidato);
            lblNumero.setVisible(true);
            lblPartido.setVisible(true);
            imprimirPartido();
            jInfoConfirma.setVisible(true);
            return;
        }
        if (txtNumero2.getText().equals("")) {
            tocarSom("SomTecla");
            txtNumero2.setText(auxNumCandidato);
            numeroCandidato.append(auxNumCandidato);
            return;
        }
        if (txtNumero3.getText().equals("")) {
            tocarSom("SomTecla");
            txtNumero3.setText(auxNumCandidato);
            numeroCandidato.append(auxNumCandidato);
            return;
        }
        if (txtNumero4.getText().equals("")) {
            tocarSom("SomTecla");
            txtNumero4.setText(auxNumCandidato);
            numeroCandidato.append(auxNumCandidato);

            try {
                if (service.getInfoCandidatos(Integer.parseInt(numeroCandidato.toString())) != null) {
                    imprimirCandidato();
                    lblNome.setVisible(true);
                }

            } catch (CandidatoInexistenteExcepition ex) {
                imprimirCandidato();
            }

        }
       
    }

    private class FinalizarVoto extends Thread {

        public void run() {

            setVisibleFinal();
            do {

                jProgressBar.setValue(jProgressBar.getValue() + 1);
                jProgressBar.setStringPainted(true);

                try {
                    if (jProgressBar.getValue() < 20 || (jProgressBar.getValue() < 85 && jProgressBar.getValue() >= 50)) {
                        sleep(10);

                        //jProgressBar.setString(jProgressBar.getValue() + "");
                    }
                    if (jProgressBar.getValue() >= 70 || (jProgressBar.getValue() >= 20 && jProgressBar.getValue() < 50)) {
                        sleep(2);
                        //jProgressBar.setValue(jProgressBar.getValue() + 1);
                        //jProgressBar.setStringPainted(true);
                        // jProgressBar.setString(jProgressBar.getValue() + "");
                    }

                } catch (InterruptedException ex) {
                }
            } while (jProgressBar.getValue() < 100);
            tocarSom("fim");
            lblFim.setVisible(true);
            jProgressBar.setVisible(false);
            try {

                sleep(2000);

            } catch (InterruptedException ex) {
                Logger.getLogger(UrnaSwing.class.getName()).log(Level.SEVERE, null, ex);
            }
            corrigir();
            iniciarVotacao();
            repaint();

        }

    }

    private void setVisibleFinal() {
        jProgressBar.setVisible(true);
        jProgressBar.setValue(0);
        jNumeros.setVisible(false);
        jInfoConfirma.setVisible(false);
        lblNomeCandidato.setVisible(false);
        lblNome.setVisible(false);
        lblNomePartido.setVisible(false);
        lblNumero.setVisible(false);
        lblPartido.setVisible(false);
        lblSeuVoto.setVisible(false);
        lblVereador.setVisible(false);
        lblImage.setVisible(false);
        lblSeuVoto.setVisible(false);
        lblMensageExeption.setVisible(false);
        lblVotoBranco.setVisible(false);
        lblMensageTipoVoto.setVisible(false);
        lblVereadora.setVisible(false);
    }

    private void tocarSom(String nomeSom) {
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(new File("").getAbsoluteFile() + "/Arquivos/audios/" + nomeSom + ".wav").getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            Logger.getLogger(UrnaSwing.class.getName()).log(Level.SEVERE, null, ex);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrnaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrnaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrnaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrnaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UrnaSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Camadas;
    private javax.swing.JPanel jInfoConfirma;
    private javax.swing.JPanel jNumeros;
    private javax.swing.JPanel jPanelInfoVereador;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JPanel jTeclado;
    private javax.swing.JLabel lblBaixoTec;
    private javax.swing.JLabel lblBranco;
    private javax.swing.JLabel lblConfirma;
    private javax.swing.JLabel lblCorrige;
    private javax.swing.JLabel lblFaixaDireita;
    private javax.swing.JLabel lblFim;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblInfoConfirma;
    private javax.swing.JLabel lblInfoCorrige;
    private javax.swing.JLabel lblInfoTeclas;
    private javax.swing.JLabel lblLadoDirTec;
    private javax.swing.JLabel lblLadoEsqTec;
    private javax.swing.JLabel lblMensageExeption;
    private javax.swing.JLabel lblMensageTipoVoto;
    private javax.swing.JLabel lblN0;
    private javax.swing.JLabel lblN1;
    private javax.swing.JLabel lblN2;
    private javax.swing.JLabel lblN3;
    private javax.swing.JLabel lblN4;
    private javax.swing.JLabel lblN5;
    private javax.swing.JLabel lblN6;
    private javax.swing.JLabel lblN7;
    private javax.swing.JLabel lblN8;
    private javax.swing.JLabel lblN9;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeCandidato;
    private javax.swing.JLabel lblNomePartido;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPartido;
    private javax.swing.JLabel lblPtaBaixo7;
    private javax.swing.JLabel lblPtaBaixo9;
    private javax.swing.JLabel lblSeuVoto;
    private javax.swing.JLabel lblTela;
    private javax.swing.JLabel lblTopo;
    private javax.swing.JLabel lblVereador;
    private javax.swing.JLabel lblVereadora;
    private javax.swing.JLabel lblVotoBranco;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    private javax.swing.JTextField txtNumero3;
    private javax.swing.JTextField txtNumero4;
    // End of variables declaration//GEN-END:variables
}
