package br.com.poo.mongo.presentation;

import br.com.poo.mongo.common.exception.CandidatoInexistenteExcepition;
import br.com.poo.mongo.common.exception.NumeroErradoException;
import br.com.poo.mongo.common.exception.VotarCandidatoInexistenteException;
import br.com.poo.mongo.common.vo.CandidatosVO;
import br.com.poo.mongo.common.vo.VotoVO;
import br.com.poo.mongo.service.ServiceCandidato;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.UIManager;
import static java.lang.Thread.sleep;
import java.text.DecimalFormat;

/**
 *
 * @author nirto
 */
public class UrnaSwing extends javax.swing.JFrame {

    private ServiceCandidato service;
    private VotoVO votos = new VotoVO();
    private List<CandidatosVO> listCandidato = new ArrayList<>();
    private CandidatosVO auxCandidato = new CandidatosVO();
    private StringBuilder impressaoFinal1 = new StringBuilder();
    private StringBuilder impressaoFinal2 = new StringBuilder();
    private StringBuilder impressaoFinal3 = new StringBuilder();
    private StringBuilder impressaoFinal4 = new StringBuilder();
    private StringBuilder impressaoFinal5 = new StringBuilder();
    private StringBuilder numeroCandidato;
    boolean votoBranco;
    private Santinho santinho = new Santinho();

    /**
     * Creates new form UrnaSwing
     */
    public UrnaSwing() {
        initComponents();
        numeroCandidato = new StringBuilder();
        service = new ServiceCandidato();
        iniciarVotacao();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/eleicaoLogo.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Camadas = new javax.swing.JLayeredPane();
        jPanelInfoVereador = new javax.swing.JPanel();
        lblFim = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblVereador = new javax.swing.JLabel();
        lblVereadora = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblPartido = new javax.swing.JLabel();
        lblNomeCandidato = new javax.swing.JLabel();
        lblNomePartido = new javax.swing.JLabel();
        lblMensageExeption = new javax.swing.JLabel();
        lblVotoBranco = new javax.swing.JLabel();
        lblSeuVoto = new javax.swing.JLabel();
        lblMensageTipoVoto = new javax.swing.JLabel();
        lblCarregando = new javax.swing.JLabel();
        UIManager.put("jProgressBar.background", new java.awt.Color(0,153,0));
        jProgressBar = new javax.swing.JProgressBar();
        jNumeros = new javax.swing.JPanel();
        txtNumero2 = new javax.swing.JTextField();
        txtNumero1 = new javax.swing.JTextField();
        txtNumero4 = new javax.swing.JTextField();
        txtNumero3 = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        jInfoConfirma = new javax.swing.JPanel();
        lblInfoTeclas = new javax.swing.JLabel();
        lblInfoConfirma = new javax.swing.JLabel();
        lblInfoCorrige = new javax.swing.JLabel();
        lblTela = new javax.swing.JLabel();
        jTeclado = new javax.swing.JPanel();
        lblAjuda = new javax.swing.JLabel();
        lblN1 = new javax.swing.JLabel();
        lblN2 = new javax.swing.JLabel();
        lblN3 = new javax.swing.JLabel();
        lblN4 = new javax.swing.JLabel();
        lblN5 = new javax.swing.JLabel();
        lblN6 = new javax.swing.JLabel();
        lblN7 = new javax.swing.JLabel();
        lblN8 = new javax.swing.JLabel();
        lblN9 = new javax.swing.JLabel();
        lblN0 = new javax.swing.JLabel();
        lblBranco = new javax.swing.JLabel();
        lblCorrige = new javax.swing.JLabel();
        lblPtaBaixo7 = new javax.swing.JLabel();
        lblBaixoTec = new javax.swing.JLabel();
        lblConfirma = new javax.swing.JLabel();
        lblPtaBaixo9 = new javax.swing.JLabel();
        lblLadoEsqTec = new javax.swing.JLabel();
        lblLadoDirTec = new javax.swing.JLabel();
        lblFaixaDireita = new javax.swing.JLabel();
        lblTopo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFinal = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextFinal1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextFinal2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextFinal3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextFinal4 = new javax.swing.JTextArea();
        lblApuracaoVotos = new javax.swing.JLabel();
        lblTitleCandidatoEleito = new javax.swing.JLabel();
        lblTotalVotosApurados = new javax.swing.JLabel();
        lblTotalVotosBrancos = new javax.swing.JLabel();
        lblTotalVotosNulos = new javax.swing.JLabel();
        lblPartido91 = new javax.swing.JLabel();
        lblPartido93 = new javax.swing.JLabel();
        lblPartido92 = new javax.swing.JLabel();
        lblPartido94 = new javax.swing.JLabel();
        lblPartido95 = new javax.swing.JLabel();
        lblVotosBrancos = new javax.swing.JLabel();
        lblCandidatoEleito = new javax.swing.JLabel();
        lblVotosApurados = new javax.swing.JLabel();
        lblVotosNulos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("br/com/poo/mongo/presentation/Bundle"); // NOI18N
        setTitle(bundle.getString("UrnaSwing.title")); // NOI18N
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(964, 618));
        setMinimumSize(new java.awt.Dimension(964, 618));
        setPreferredSize(new java.awt.Dimension(990, 650));
        setResizable(false);

        Camadas.setBackground(new java.awt.Color(255, 255, 255));
        Camadas.setForeground(new java.awt.Color(255, 255, 255));
        Camadas.setAutoscrolls(true);
        Camadas.setDoubleBuffered(true);
        Camadas.setFocusCycleRoot(true);
        Camadas.setFocusTraversalPolicyProvider(true);
        Camadas.setMaximumSize(new java.awt.Dimension(1000, 610));
        Camadas.setMinimumSize(new java.awt.Dimension(1000, 610));
        Camadas.setOpaque(true);
        Camadas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelInfoVereador.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInfoVereador.setMaximumSize(new java.awt.Dimension(2147483647, 588));
        jPanelInfoVereador.setMinimumSize(new java.awt.Dimension(632, 588));
        jPanelInfoVereador.setPreferredSize(new java.awt.Dimension(632, 588));
        jPanelInfoVereador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFim.setFont(new java.awt.Font("Arial", 0, 150)); // NOI18N
        lblFim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFim.setText(bundle.getString("UrnaSwing.lblFim.text")); // NOI18N
        jPanelInfoVereador.add(lblFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 320, 240));

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblImage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblImage.setMaximumSize(new java.awt.Dimension(112, 116));
        lblImage.setMinimumSize(new java.awt.Dimension(112, 116));
        lblImage.setPreferredSize(new java.awt.Dimension(112, 116));
        jPanelInfoVereador.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 112, 116));

        lblVereador.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        lblVereador.setText(bundle.getString("UrnaSwing.lblVereador.text")); // NOI18N
        lblVereador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelInfoVereador.add(lblVereador, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        lblVereadora.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        lblVereadora.setText(bundle.getString("UrnaSwing.lblVereadora.text")); // NOI18N
        lblVereadora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelInfoVereador.add(lblVereadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        lblNumero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNumero.setText(bundle.getString("UrnaSwing.lblNumero.text")); // NOI18N
        lblNumero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelInfoVereador.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        lblNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNome.setText(bundle.getString("UrnaSwing.lblNome.text")); // NOI18N
        lblNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelInfoVereador.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        lblPartido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPartido.setText(bundle.getString("UrnaSwing.lblPartido.text")); // NOI18N
        lblPartido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelInfoVereador.add(lblPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        lblNomeCandidato.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblNomeCandidato.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomeCandidato.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelInfoVereador.add(lblNomeCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 200, 20));

        lblNomePartido.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblNomePartido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomePartido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblNomePartido.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanelInfoVereador.add(lblNomePartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 40, 30));

        lblMensageExeption.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblMensageExeption.setText(bundle.getString("UrnaSwing.lblMensageExeption.text")); // NOI18N
        jPanelInfoVereador.add(lblMensageExeption, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 360, 30));

        lblVotoBranco.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblVotoBranco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVotoBranco.setText(bundle.getString("UrnaSwing.lblVotoBranco.text")); // NOI18N
        jPanelInfoVereador.add(lblVotoBranco, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 325, 410, 90));

        lblSeuVoto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSeuVoto.setText(bundle.getString("UrnaSwing.lblSeuVoto.text")); // NOI18N
        lblSeuVoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelInfoVereador.add(lblSeuVoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 130, 30));

        lblMensageTipoVoto.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblMensageTipoVoto.setText(bundle.getString("UrnaSwing.lblMensageTipoVoto.text")); // NOI18N
        jPanelInfoVereador.add(lblMensageTipoVoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 350, 50));

        lblCarregando.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblCarregando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarregando.setText(bundle.getString("UrnaSwing.lblCarregando.text")); // NOI18N
        lblCarregando.setAutoscrolls(true);
        lblCarregando.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelInfoVereador.add(lblCarregando, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 405, 400, 20));

        jProgressBar.setBackground(new java.awt.Color(0, 153, 0));
        jProgressBar.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jProgressBar.setForeground(new java.awt.Color(0, 0, 0));
        jProgressBar.setAutoscrolls(true);
        jProgressBar.setBorderPainted(false);
        jProgressBar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jProgressBar.setDoubleBuffered(true);
        jProgressBar.setFocusCycleRoot(true);
        jProgressBar.setFocusTraversalPolicyProvider(true);
        jProgressBar.setInheritsPopupMenu(true);
        jProgressBar.setName(""); // NOI18N
        jProgressBar.setStringPainted(true);
        jPanelInfoVereador.add(jProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 400, 30));

        jNumeros.setBackground(new java.awt.Color(214, 214, 214));
        jNumeros.setOpaque(false);
        jNumeros.setLayout(new java.awt.GridBagLayout());

        txtNumero2.setEditable(false);
        txtNumero2.setBackground(new java.awt.Color(214, 214, 214));
        txtNumero2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtNumero2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNumero2.setFocusable(false);
        txtNumero2.setRequestFocusEnabled(false);
        txtNumero2.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jNumeros.add(txtNumero2, gridBagConstraints);

        txtNumero1.setEditable(false);
        txtNumero1.setBackground(new java.awt.Color(214, 214, 214));
        txtNumero1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtNumero1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNumero1.setFocusable(false);
        txtNumero1.setRequestFocusEnabled(false);
        txtNumero1.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jNumeros.add(txtNumero1, gridBagConstraints);

        txtNumero4.setEditable(false);
        txtNumero4.setBackground(new java.awt.Color(214, 214, 214));
        txtNumero4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtNumero4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNumero4.setFocusable(false);
        txtNumero4.setMaximumSize(new java.awt.Dimension(7, 20));
        txtNumero4.setRequestFocusEnabled(false);
        txtNumero4.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jNumeros.add(txtNumero4, gridBagConstraints);

        txtNumero3.setEditable(false);
        txtNumero3.setBackground(new java.awt.Color(214, 214, 214));
        txtNumero3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtNumero3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNumero3.setFocusable(false);
        txtNumero3.setRequestFocusEnabled(false);
        txtNumero3.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jNumeros.add(txtNumero3, gridBagConstraints);

        txtNumero.setEditable(false);
        txtNumero.setBackground(new java.awt.Color(214, 214, 214));
        txtNumero.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero.setText(bundle.getString("UrnaSwing.txtNumero.text")); // NOI18N
        txtNumero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNumero.setFocusable(false);
        txtNumero.setRequestFocusEnabled(false);
        txtNumero.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtNumero.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jNumeros.add(txtNumero, gridBagConstraints);

        jPanelInfoVereador.add(jNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, 40));

        jInfoConfirma.setBackground(new java.awt.Color(214, 214, 214));
        jInfoConfirma.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jInfoConfirma.setMaximumSize(new java.awt.Dimension(549, 77));
        jInfoConfirma.setMinimumSize(new java.awt.Dimension(549, 77));
        jInfoConfirma.setLayout(new java.awt.GridBagLayout());

        lblInfoTeclas.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lblInfoTeclas.setText(bundle.getString("UrnaSwing.lblInfoTeclas.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jInfoConfirma.add(lblInfoTeclas, gridBagConstraints);

        lblInfoConfirma.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lblInfoConfirma.setText(bundle.getString("UrnaSwing.lblInfoConfirma.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 0);
        jInfoConfirma.add(lblInfoConfirma, gridBagConstraints);

        lblInfoCorrige.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lblInfoCorrige.setText(bundle.getString("UrnaSwing.lblInfoCorrige.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 24, 0, 0);
        jInfoConfirma.add(lblInfoCorrige, gridBagConstraints);

        jPanelInfoVereador.add(jInfoConfirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 464, 549, 77));

        lblTela.setBackground(new java.awt.Color(255, 255, 255));
        lblTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/tela.jpg"))); // NOI18N
        lblTela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelInfoVereador.add(lblTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 14, 642, 603));

        Camadas.add(jPanelInfoVereador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 590));

        jTeclado.setBackground(new java.awt.Color(255, 255, 255));
        jTeclado.setAutoscrolls(true);
        jTeclado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTeclado.setMaximumSize(new java.awt.Dimension(324, 588));
        jTeclado.setMinimumSize(new java.awt.Dimension(324, 588));
        jTeclado.setPreferredSize(new java.awt.Dimension(324, 588));
        jTeclado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/ajuda.jpg"))); // NOI18N
        lblAjuda.setText(bundle.getString("UrnaSwing.lblAjuda.text")); // NOI18N
        lblAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAjudaMouseClicked(evt);
            }
        });
        jTeclado.add(lblAjuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        lblN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n1.jpg"))); // NOI18N
        lblN1.setAlignmentY(0.0F);
        lblN1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN1MouseReleased(evt);
            }
        });
        jTeclado.add(lblN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 261, -1, -1));

        lblN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n2.jpg"))); // NOI18N
        lblN2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN2MouseReleased(evt);
            }
        });
        jTeclado.add(lblN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 261, -1, -1));

        lblN3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n3.jpg"))); // NOI18N
        lblN3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN3MouseReleased(evt);
            }
        });
        jTeclado.add(lblN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 261, -1, -1));

        lblN4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n4.jpg"))); // NOI18N
        lblN4.setAlignmentY(0.0F);
        lblN4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN4MouseReleased(evt);
            }
        });
        jTeclado.add(lblN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 319, -1, -1));

        lblN5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n5.jpg"))); // NOI18N
        lblN5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN5MouseReleased(evt);
            }
        });
        jTeclado.add(lblN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 319, -1, -1));

        lblN6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n6.jpg"))); // NOI18N
        lblN6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN6MouseReleased(evt);
            }
        });
        jTeclado.add(lblN6, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 319, -1, -1));

        lblN7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n7.jpg"))); // NOI18N
        lblN7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN7MouseReleased(evt);
            }
        });
        jTeclado.add(lblN7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 379, -1, -1));

        lblN8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n8.jpg"))); // NOI18N
        lblN8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN8MouseReleased(evt);
            }
        });
        jTeclado.add(lblN8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 379, -1, -1));

        lblN9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n9.jpg"))); // NOI18N
        lblN9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN9MouseReleased(evt);
            }
        });
        jTeclado.add(lblN9, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 379, -1, -1));

        lblN0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/n0.jpg"))); // NOI18N
        lblN0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblN0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblN0MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblN0MouseReleased(evt);
            }
        });
        jTeclado.add(lblN0, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 437, -1, -1));

        lblBranco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/branco.jpg"))); // NOI18N
        lblBranco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBranco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBrancoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBrancoMouseReleased(evt);
            }
        });
        jTeclado.add(lblBranco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 487, -1, -1));

        lblCorrige.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/corrige.jpg"))); // NOI18N
        lblCorrige.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCorrige.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCorrigeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblCorrigeMouseReleased(evt);
            }
        });
        jTeclado.add(lblCorrige, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 487, -1, -1));

        lblPtaBaixo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/ptabaixo7.jpg"))); // NOI18N
        jTeclado.add(lblPtaBaixo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 437, -1, -1));

        lblBaixoTec.setBackground(new java.awt.Color(255, 255, 255));
        lblBaixoTec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/abaixoTec.jpg"))); // NOI18N
        jTeclado.add(lblBaixoTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 546, -1, -1));

        lblConfirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/confirma.jpg"))); // NOI18N
        lblConfirma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblConfirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblConfirmaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblConfirmaMouseReleased(evt);
            }
        });
        jTeclado.add(lblConfirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 476, -1, -1));

        lblPtaBaixo9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/ptabaixo9.jpg"))); // NOI18N
        jTeclado.add(lblPtaBaixo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 437, -1, -1));

        lblLadoEsqTec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/ladoEsqTec.jpg"))); // NOI18N
        jTeclado.add(lblLadoEsqTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 261, -1, -1));

        lblLadoDirTec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/ladoDirTec.jpg"))); // NOI18N
        jTeclado.add(lblLadoDirTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 261, -1, -1));

        lblFaixaDireita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/faixaDir.jpg"))); // NOI18N
        jTeclado.add(lblFaixaDireita, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 35, -1, -1));

        lblTopo.setBackground(new java.awt.Color(255, 255, 255));
        lblTopo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo/images/urna/topo.jpg"))); // NOI18N
        jTeclado.add(lblTopo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Camadas.add(jTeclado, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 11, 370, 580));

        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 610));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 610));

        jTextFinal.setEditable(false);
        jTextFinal.setColumns(20);
        jTextFinal.setLineWrap(true);
        jTextFinal.setRows(5);
        jTextFinal.setText(bundle.getString("UrnaSwing.jTextFinal.text")); // NOI18N
        jTextFinal.setMaximumSize(new java.awt.Dimension(164, 74));
        jTextFinal.setMinimumSize(new java.awt.Dimension(164, 74));
        jScrollPane1.setViewportView(jTextFinal);

        jTextFinal1.setEditable(false);
        jTextFinal1.setColumns(20);
        jTextFinal1.setRows(5);
        jTextFinal1.setText(bundle.getString("UrnaSwing.jTextFinal1.text")); // NOI18N
        jTextFinal1.setMaximumSize(new java.awt.Dimension(164, 74));
        jTextFinal1.setMinimumSize(new java.awt.Dimension(164, 74));
        jTextFinal1.setPreferredSize(new java.awt.Dimension(164, 74));
        jScrollPane2.setViewportView(jTextFinal1);

        jTextFinal2.setEditable(false);
        jTextFinal2.setColumns(20);
        jTextFinal2.setRows(5);
        jTextFinal2.setText(bundle.getString("UrnaSwing.jTextFinal2.text")); // NOI18N
        jTextFinal2.setMaximumSize(new java.awt.Dimension(164, 74));
        jTextFinal2.setMinimumSize(new java.awt.Dimension(164, 74));
        jTextFinal2.setPreferredSize(new java.awt.Dimension(164, 74));
        jScrollPane3.setViewportView(jTextFinal2);

        jTextFinal3.setEditable(false);
        jTextFinal3.setColumns(20);
        jTextFinal3.setRows(5);
        jTextFinal3.setText(bundle.getString("UrnaSwing.jTextFinal3.text")); // NOI18N
        jTextFinal3.setMaximumSize(new java.awt.Dimension(164, 74));
        jTextFinal3.setMinimumSize(new java.awt.Dimension(164, 74));
        jTextFinal3.setPreferredSize(new java.awt.Dimension(164, 74));
        jScrollPane4.setViewportView(jTextFinal3);

        jTextFinal4.setEditable(false);
        jTextFinal4.setColumns(20);
        jTextFinal4.setRows(5);
        jTextFinal4.setText(bundle.getString("UrnaSwing.jTextFinal4.text")); // NOI18N
        jTextFinal4.setMaximumSize(new java.awt.Dimension(164, 74));
        jTextFinal4.setMinimumSize(new java.awt.Dimension(164, 74));
        jTextFinal4.setName(""); // NOI18N
        jTextFinal4.setPreferredSize(new java.awt.Dimension(164, 74));
        jScrollPane5.setViewportView(jTextFinal4);

        lblApuracaoVotos.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblApuracaoVotos.setText(bundle.getString("UrnaSwing.lblApuracaoVotos.text")); // NOI18N

        lblTitleCandidatoEleito.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTitleCandidatoEleito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleCandidatoEleito.setText(bundle.getString("UrnaSwing.lblTitleCandidatoEleito.text")); // NOI18N

        lblTotalVotosApurados.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTotalVotosApurados.setText(bundle.getString("UrnaSwing.lblTotalVotosApurados.text")); // NOI18N

        lblTotalVotosBrancos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTotalVotosBrancos.setText(bundle.getString("UrnaSwing.lblTotalVotosBrancos.text")); // NOI18N

        lblTotalVotosNulos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTotalVotosNulos.setText(bundle.getString("UrnaSwing.lblTotalVotosNulos.text")); // NOI18N

        lblPartido91.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPartido91.setText(bundle.getString("UrnaSwing.lblPartido91.text")); // NOI18N

        lblPartido93.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPartido93.setText(bundle.getString("UrnaSwing.lblPartido93.text")); // NOI18N

        lblPartido92.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPartido92.setText(bundle.getString("UrnaSwing.lblPartido92.text")); // NOI18N

        lblPartido94.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPartido94.setText(bundle.getString("UrnaSwing.lblPartido94.text")); // NOI18N

        lblPartido95.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPartido95.setText(bundle.getString("UrnaSwing.lblPartido95.text")); // NOI18N

        lblVotosBrancos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblVotosBrancos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVotosBrancos.setText(bundle.getString("UrnaSwing.lblVotosBrancos.text")); // NOI18N
        lblVotosBrancos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblCandidatoEleito.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCandidatoEleito.setForeground(new java.awt.Color(255, 0, 0));
        lblCandidatoEleito.setText(bundle.getString("UrnaSwing.lblCandidatoEleito.text")); // NOI18N

        lblVotosApurados.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblVotosApurados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVotosApurados.setText(bundle.getString("UrnaSwing.lblVotosApurados.text")); // NOI18N
        lblVotosApurados.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblVotosNulos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblVotosNulos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVotosNulos.setText(bundle.getString("UrnaSwing.lblVotosNulos.text")); // NOI18N
        lblVotosNulos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblVotosNulos.setMaximumSize(new java.awt.Dimension(8, 17));
        lblVotosNulos.setMinimumSize(new java.awt.Dimension(8, 17));
        lblVotosNulos.setPreferredSize(new java.awt.Dimension(8, 17));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblPartido92))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblPartido91)))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblPartido93))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblPartido94)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTitleCandidatoEleito)
                                .addGap(18, 18, 18)
                                .addComponent(lblCandidatoEleito, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotalVotosApurados)
                                    .addComponent(lblTotalVotosNulos)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(lblTotalVotosBrancos)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblVotosApurados, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblVotosBrancos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblVotosNulos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblPartido95, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblApuracaoVotos, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblApuracaoVotos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPartido93)
                            .addComponent(lblPartido91))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPartido92, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPartido94, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitleCandidatoEleito, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCandidatoEleito, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(lblTotalVotosApurados))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVotosApurados, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotalVotosNulos)
                            .addComponent(lblVotosNulos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVotosBrancos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalVotosBrancos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPartido95)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Camadas.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Camadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Camadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void lblN1MousePressed(MouseEvent evt) {//GEN-FIRST:event_lblN1MousePressed
        lblN1.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n1_down.jpg"));
        testarIndiceNumeroCandidato("1");

    }//GEN-LAST:event_lblN1MousePressed


    private void lblN1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN1MouseReleased
        lblN1.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n1.jpg"));
    }//GEN-LAST:event_lblN1MouseReleased

    private void lblN2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN2MousePressed
        lblN2.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n2_down.jpg"));
        testarIndiceNumeroCandidato("2");
    }//GEN-LAST:event_lblN2MousePressed

    private void lblN2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN2MouseReleased
        lblN2.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n2.jpg"));
    }//GEN-LAST:event_lblN2MouseReleased

    private void lblN3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN3MousePressed
        lblN3.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n3_down.jpg"));
        testarIndiceNumeroCandidato("3");
    }//GEN-LAST:event_lblN3MousePressed

    private void lblN3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN3MouseReleased
        lblN3.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n3.jpg"));
    }//GEN-LAST:event_lblN3MouseReleased

    private void lblN4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN4MousePressed
        lblN4.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n4_down.jpg"));
        testarIndiceNumeroCandidato("4");
    }//GEN-LAST:event_lblN4MousePressed

    private void lblN4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN4MouseReleased
        lblN4.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n4.jpg"));
    }//GEN-LAST:event_lblN4MouseReleased

    private void lblN5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN5MousePressed
        lblN5.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n5_down.jpg"));
        testarIndiceNumeroCandidato("5");
    }//GEN-LAST:event_lblN5MousePressed

    private void lblN5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN5MouseReleased
        lblN5.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n5.jpg"));
    }//GEN-LAST:event_lblN5MouseReleased

    private void lblN6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN6MousePressed
        lblN6.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n6_down.jpg"));
        testarIndiceNumeroCandidato("6");
    }//GEN-LAST:event_lblN6MousePressed

    private void lblN6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN6MouseReleased
        lblN6.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n6.jpg"));
    }//GEN-LAST:event_lblN6MouseReleased

    private void lblN7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN7MousePressed
        lblN7.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n7_down.jpg"));
        testarIndiceNumeroCandidato("7");
    }//GEN-LAST:event_lblN7MousePressed

    private void lblN7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN7MouseReleased
        lblN7.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n7.jpg"));
    }//GEN-LAST:event_lblN7MouseReleased

    private void lblN8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN8MousePressed
        lblN8.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n8_down.jpg"));
        testarIndiceNumeroCandidato("8");
    }//GEN-LAST:event_lblN8MousePressed

    private void lblN8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN8MouseReleased
        lblN8.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n8.jpg"));
    }//GEN-LAST:event_lblN8MouseReleased

    private void lblN9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN9MousePressed
        lblN9.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n9_down.jpg"));
        testarIndiceNumeroCandidato("9");
    }//GEN-LAST:event_lblN9MousePressed

    private void lblN9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN9MouseReleased
        lblN9.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n9.jpg"));
    }//GEN-LAST:event_lblN9MouseReleased

    private void lblN0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN0MousePressed
        lblN0.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n0_down.jpg"));
        testarIndiceNumeroCandidato("0");
    }//GEN-LAST:event_lblN0MousePressed

    private void lblN0MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblN0MouseReleased
        lblN0.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/n0.jpg"));
    }//GEN-LAST:event_lblN0MouseReleased

    private void lblBrancoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBrancoMousePressed
        lblBranco.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/branco_down.jpg"));
        tocarSom("SomTecla");
        jNumeros.setVisible(false);
        lblVotoBranco.setText("VOTO EM BRANCO");
        lblSeuVoto.setVisible(true);
        lblVotoBranco.setVisible(true);
        votoBranco = true;
        jInfoConfirma.setVisible(true);
        lblMensageTipoVoto.setVisible(false);
        lblVereadora.setVisible(false);
    }//GEN-LAST:event_lblBrancoMousePressed

    private void lblBrancoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBrancoMouseReleased
        lblBranco.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/branco.jpg"));
    }//GEN-LAST:event_lblBrancoMouseReleased

    private void lblCorrigeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCorrigeMousePressed
        lblCorrige.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/corrige_down.jpg"));
        tocarSom("SomTecla");
        corrigir();
    }//GEN-LAST:event_lblCorrigeMousePressed


    private void lblCorrigeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCorrigeMouseReleased
        lblCorrige.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/corrige.jpg"));
    }//GEN-LAST:event_lblCorrigeMouseReleased

    private void lblConfirmaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmaMousePressed
        lblConfirma.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/confirma_down.jpg"));

        if (numeroCandidato.toString().equals("99999")) {
           new ImprimirResultado().start();
            return;
        }
        if (votoBranco) {
            votos.votarBranco();
            votos.somaTotalVotos();
        } else {
            try {
                service.votar(Integer.parseInt(numeroCandidato.toString()));
                // auxCandidato.receberVoto();
                votos.somaTotalVotos();
            } catch (VotarCandidatoInexistenteException ex) {
                votos.somaTotalVotos();
                votos.votarNulo();
            }
        }
        tocarSom("inter");
        new FinalizarVoto().start();


    }//GEN-LAST:event_lblConfirmaMousePressed

    private void lblConfirmaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmaMouseReleased
        lblConfirma.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/urna/confirma.jpg"));
    }//GEN-LAST:event_lblConfirmaMouseReleased

    private void lblAjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAjudaMouseClicked
        santinho = new Santinho();
        santinho.setLocationRelativeTo(null);
        santinho.setVisible(true);
        santinho.setResizable(false);
    }//GEN-LAST:event_lblAjudaMouseClicked

    private void iniciarVotacao() {
        jPanelInfoVereador.setVisible(true);
        lblNome.setVisible(false);
        lblNumero.setVisible(false);
        lblVereador.setVisible(true);
        lblPartido.setVisible(false);
        lblNomePartido.setText("");
        lblNomeCandidato.setText("");
        lblImage.setVisible(false);
        lblSeuVoto.setVisible(false);
        jInfoConfirma.setVisible(false);
        jProgressBar.setVisible(false);
        jNumeros.setVisible(true);
        lblNomePartido.setVisible(true);
        lblNomeCandidato.setVisible(true);
        lblFim.setText("FIM");
        lblFim.setVisible(false);
        lblMensageExeption.setVisible(false);
        lblVotoBranco.setVisible(false);
        votoBranco = false;
        lblMensageTipoVoto.setVisible(false);
        lblVereadora.setVisible(false);
        jTextFinal.setVisible(false);
        jScrollPane1.setVisible(false);
        jPanel1.setVisible(false);
    }

    private void imprimirPartido() {
        try {
            auxCandidato = service.getInfoPartido(Integer.parseInt(numeroCandidato.toString()));
            lblNomePartido.setText(auxCandidato.getPartido());
            lblSeuVoto.setVisible(true);
        } catch (NumeroErradoException ex) {
            lblMensageExeption.setVisible(true);
            lblMensageExeption.setText(ex.getMessage());
            lblMensageTipoVoto.setVisible(true);
            lblMensageTipoVoto.setText("VOTO NULO");
        }
    }

    private void imprimirCandidato() {
        try {
            auxCandidato = service.getInfoCandidatos(Integer.parseInt(numeroCandidato.toString()));
            if (auxCandidato.getNumeroCandidato() == 91003 || auxCandidato.getNumeroCandidato() == 92003
                    || auxCandidato.getNumeroCandidato() == 93003 || auxCandidato.getNumeroCandidato() == 94001
                    || auxCandidato.getNumeroCandidato() == 94002 || auxCandidato.getNumeroCandidato() == 95002
                    || auxCandidato.getNumeroCandidato() == 95003) {
                lblVereadora.setVisible(true);
            }
            lblImage.setVisible(true);
            lblImage.setIcon(new javax.swing.ImageIcon("" + new File("").getAbsoluteFile() + "/Arquivos/images/candidatos/" + auxCandidato.getNumeroCandidato() + ".png"));
            lblNomeCandidato.setText(auxCandidato.getNome());
        } catch (CandidatoInexistenteExcepition ex) {
            lblNome.setVisible(false);
            lblMensageExeption.setVisible(true);
            lblMensageExeption.setText(ex.getMessage());
            lblMensageTipoVoto.setVisible(true);
            lblMensageTipoVoto.setText("VOTO NULO");
        }

    }

    private void corrigir() {

        txtNumero.setText("");
        txtNumero1.setText("");
        txtNumero2.setText("");
        txtNumero3.setText("");
        txtNumero4.setText("");
        lblNomeCandidato.setText("");
        lblNomePartido.setText("");
        lblNome.setVisible(false);
        lblNumero.setVisible(false);
        lblPartido.setVisible(false);
        lblImage.setIcon(null);
        lblImage.setVisible(false);
        numeroCandidato.setLength(0);
        jInfoConfirma.setVisible(false);
        lblSeuVoto.setVisible(false);
        lblMensageExeption.setVisible(false);
        lblVotoBranco.setVisible(false);
        jNumeros.setVisible(true);
        lblMensageTipoVoto.setVisible(false);
        lblVereadora.setVisible(false);
    }

    private void testarIndiceNumeroCandidato(String auxNumCandidato) {
        if (txtNumero.getText().equals("")) {
            tocarSom("SomTecla");
            txtNumero.setText(auxNumCandidato);
            numeroCandidato.append(auxNumCandidato);
            return;
        }
        if (txtNumero1.getText().equals("")) {
            tocarSom("SomTecla");
            txtNumero1.setText(auxNumCandidato);
            numeroCandidato.append(auxNumCandidato);
            lblNumero.setVisible(true);
            lblPartido.setVisible(true);
            imprimirPartido();
            jInfoConfirma.setVisible(true);
            return;
        }
        if (txtNumero2.getText().equals("")) {
            tocarSom("SomTecla");
            txtNumero2.setText(auxNumCandidato);
            numeroCandidato.append(auxNumCandidato);
            return;
        }
        if (txtNumero3.getText().equals("")) {
            tocarSom("SomTecla");
            txtNumero3.setText(auxNumCandidato);
            numeroCandidato.append(auxNumCandidato);
            return;
        }
        if (txtNumero4.getText().equals("")) {
            tocarSom("SomTecla");
            txtNumero4.setText(auxNumCandidato);
            numeroCandidato.append(auxNumCandidato);
            try {
                if (service.getInfoCandidatos(Integer.parseInt(numeroCandidato.toString())) != null) {
                    imprimirCandidato();
                    lblNome.setVisible(true);
                }
            } catch (CandidatoInexistenteExcepition ex) {
                imprimirCandidato();
            }

        }

    }

    private class FinalizarVoto extends Thread {

        public void run() {

            setVisibleFinal();
            jProgressBar.setMaximum(100);
            do {
                jProgressBar.setValue(jProgressBar.getValue() + 1);
                jProgressBar.setStringPainted(true);
                try {
                    if (jProgressBar.getValue() < 20 || (jProgressBar.getValue() < 85 && jProgressBar.getValue() >= 50)) {
                        sleep(10);
                    }
                    if (jProgressBar.getValue() >= 70 || (jProgressBar.getValue() >= 20 && jProgressBar.getValue() < 50)) {
                        sleep(2);
                    }

                } catch (InterruptedException ex) {
                }
            } while (jProgressBar.getValue() < jProgressBar.getMaximum());
            tocarSom("fim");
            lblFim.setVisible(true);
            jProgressBar.setVisible(false);
            try {
                sleep(2000);
            } catch (InterruptedException ex) {
                Logger.getLogger(UrnaSwing.class.getName()).log(Level.SEVERE, null, ex);
            }
            corrigir();
            iniciarVotacao();
            repaint();

        }

    }

    
    private class ImprimirResultado extends Thread {

        public void run() {

            setVisibleFinal();
            jProgressBar.setMaximum(1000);
            do {
                jProgressBar.setValue(jProgressBar.getValue() + 1);
                jProgressBar.setStringPainted(true);
                if(jProgressBar.getValue() < 250){
                    lblCarregando.setText("Carregando......");
                }
                else if(jProgressBar.getValue() >= 250 && jProgressBar.getValue() < 750){
                    lblCarregando.setText("Calculando os votos......");
                }
                else{
                    lblCarregando.setText("Fechando conexão com o banco de dados......");
                }
                
                try {
                    if (jProgressBar.getValue() < 200 || (jProgressBar.getValue() < 850 && jProgressBar.getValue() >= 500)) {
                        sleep(9);
                        
                    }
                    if (jProgressBar.getValue() >= 700 || (jProgressBar.getValue() >= 200 && jProgressBar.getValue() < 500)) {
                        sleep(3);
                        
                    }

                } catch (InterruptedException ex) {
                }
            } while (jProgressBar.getValue() < jProgressBar.getMaximum());
            
            try {
                lblCarregando.setText("Imprimindo......");
                sleep(2000);
            } catch (InterruptedException ex) {
                Logger.getLogger(UrnaSwing.class.getName()).log(Level.SEVERE, null, ex);
            }
            criarListCandidatos();
            mostrarResultadoFinal();

        }

    }
    
    private void setVisibleFinal() {
        jProgressBar.setVisible(true);
        jProgressBar.setValue(0);
        jNumeros.setVisible(false);
        jInfoConfirma.setVisible(false);
        lblNomeCandidato.setVisible(false);
        lblNome.setVisible(false);
        lblNomePartido.setVisible(false);
        lblNumero.setVisible(false);
        lblPartido.setVisible(false);
        lblSeuVoto.setVisible(false);
        lblVereador.setVisible(false);
        lblImage.setVisible(false);
        lblSeuVoto.setVisible(false);
        lblMensageExeption.setVisible(false);
        lblVotoBranco.setVisible(false);
        lblMensageTipoVoto.setVisible(false);
        lblVereadora.setVisible(false);
    }

    private void criarListCandidatos() {
        for (int i = 91000; i < 96000; i += 1000) {
            for (int j = 1; j < 4; j++) {
                listCandidato.add(service.getInfoCandidatos(i + j));
            }
        }
    }

    private String calcularPorcentagem(double votoCandidato) {

        return new DecimalFormat("0.00").format((votoCandidato / votos.getTotalVotos()) * 100);
    }

    private void mostrarResultadoFinal() {
        ArrayList<CandidatosVO> listaOrdenada = (ArrayList<CandidatosVO>) listCandidato.stream()
                .sorted(Comparator.comparing(CandidatosVO::getVotos).reversed())
                .collect(Collectors.toList());

        for (CandidatosVO candidato : listaOrdenada) {
            switch (candidato.getNumPartido()) {
                case 91:

                    impressaoFinal1.append(candidato.toString());
                    impressaoFinal1.append("\t(");
                    impressaoFinal1.append(calcularPorcentagem(candidato.getVotos()));
                    impressaoFinal1.append("%)");
                    impressaoFinal1.append("\n\n");
                    break;
                case 92:
                    impressaoFinal2.append(candidato.toString());
                    impressaoFinal2.append("\t(");
                    impressaoFinal2.append(calcularPorcentagem(candidato.getVotos()));
                    impressaoFinal2.append("%)");
                    impressaoFinal2.append("\n\n");
                    break;
                case 93:
                    impressaoFinal3.append(candidato.toString());
                    impressaoFinal3.append("\t(");
                    impressaoFinal3.append(calcularPorcentagem(candidato.getVotos()));
                    impressaoFinal3.append("%)");
                    impressaoFinal3.append("\n\n");
                    break;
                case 94:
                    impressaoFinal4.append(candidato.toString());
                    impressaoFinal4.append("\t(");
                    impressaoFinal4.append(calcularPorcentagem(candidato.getVotos()));
                    impressaoFinal4.append("%)");
                    impressaoFinal4.append("\n\n");
                    break;
                case 95:
                    impressaoFinal5.append(candidato.toString());
                    impressaoFinal5.append("\t(");
                    impressaoFinal5.append(calcularPorcentagem(candidato.getVotos()));
                    impressaoFinal5.append("%)");
                    impressaoFinal5.append("\n\n");
                    break;
                default:
                    break;
            }

        }
        jTextFinal.setText(impressaoFinal1.toString());
        jTextFinal1.setText(impressaoFinal2.toString());
        jTextFinal2.setText(impressaoFinal3.toString());
        jTextFinal3.setText(impressaoFinal4.toString());
        jTextFinal4.setText(impressaoFinal5.toString());
        if (votos.getTotalVotos() > 0) {
            lblCandidatoEleito.setText(listaOrdenada.get(0).getNome() + "   " + "(" + calcularPorcentagem(listaOrdenada.get(0).getVotos()) + "%)");
        }
        lblVotosApurados.setText("" + votos.getTotalVotos());
        lblVotosBrancos.setText("" + votos.getVotosBrancos());
        lblVotosNulos.setText("" + votos.getVotosNulos());
        jPanel1.setVisible(true);
        jTeclado.setVisible(false);
        jPanelInfoVereador.setVisible(false);
        jTextFinal.setVisible(true);
        jScrollPane1.setVisible(true);
    }

    private void tocarSom(String nomeSom) {
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(new File("").getAbsoluteFile() + "/Arquivos/audios/" + nomeSom + ".wav").getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            Logger.getLogger(UrnaSwing.class.getName()).log(Level.SEVERE, null, ex);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrnaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrnaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrnaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrnaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UrnaSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Camadas;
    private javax.swing.JPanel jInfoConfirma;
    private javax.swing.JPanel jNumeros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelInfoVereador;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel jTeclado;
    private javax.swing.JTextArea jTextFinal;
    private javax.swing.JTextArea jTextFinal1;
    private javax.swing.JTextArea jTextFinal2;
    private javax.swing.JTextArea jTextFinal3;
    private javax.swing.JTextArea jTextFinal4;
    private javax.swing.JLabel lblAjuda;
    private javax.swing.JLabel lblApuracaoVotos;
    private javax.swing.JLabel lblBaixoTec;
    private javax.swing.JLabel lblBranco;
    private javax.swing.JLabel lblCandidatoEleito;
    private javax.swing.JLabel lblCarregando;
    private javax.swing.JLabel lblConfirma;
    private javax.swing.JLabel lblCorrige;
    private javax.swing.JLabel lblFaixaDireita;
    private javax.swing.JLabel lblFim;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblInfoConfirma;
    private javax.swing.JLabel lblInfoCorrige;
    private javax.swing.JLabel lblInfoTeclas;
    private javax.swing.JLabel lblLadoDirTec;
    private javax.swing.JLabel lblLadoEsqTec;
    private javax.swing.JLabel lblMensageExeption;
    private javax.swing.JLabel lblMensageTipoVoto;
    private javax.swing.JLabel lblN0;
    private javax.swing.JLabel lblN1;
    private javax.swing.JLabel lblN2;
    private javax.swing.JLabel lblN3;
    private javax.swing.JLabel lblN4;
    private javax.swing.JLabel lblN5;
    private javax.swing.JLabel lblN6;
    private javax.swing.JLabel lblN7;
    private javax.swing.JLabel lblN8;
    private javax.swing.JLabel lblN9;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeCandidato;
    private javax.swing.JLabel lblNomePartido;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPartido;
    private javax.swing.JLabel lblPartido91;
    private javax.swing.JLabel lblPartido92;
    private javax.swing.JLabel lblPartido93;
    private javax.swing.JLabel lblPartido94;
    private javax.swing.JLabel lblPartido95;
    private javax.swing.JLabel lblPtaBaixo7;
    private javax.swing.JLabel lblPtaBaixo9;
    private javax.swing.JLabel lblSeuVoto;
    private javax.swing.JLabel lblTela;
    private javax.swing.JLabel lblTitleCandidatoEleito;
    private javax.swing.JLabel lblTopo;
    private javax.swing.JLabel lblTotalVotosApurados;
    private javax.swing.JLabel lblTotalVotosBrancos;
    private javax.swing.JLabel lblTotalVotosNulos;
    private javax.swing.JLabel lblVereador;
    private javax.swing.JLabel lblVereadora;
    private javax.swing.JLabel lblVotoBranco;
    private javax.swing.JLabel lblVotosApurados;
    private javax.swing.JLabel lblVotosBrancos;
    private javax.swing.JLabel lblVotosNulos;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    private javax.swing.JTextField txtNumero3;
    private javax.swing.JTextField txtNumero4;
    // End of variables declaration//GEN-END:variables
}
